insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Shirts","clothes", 10000, "Adidas", 100, "운동복 상의예요!")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Pants","clothes", 15000, "Adidas", 50, "운동복 하의예요!!")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("TV","appliances", 1000000, "Samsung", 10, "OLED!")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Microwave","appliances", 500000, "SK", 40, "고급형 전자레인지!")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Refrigerator","appliances", 3000000, "LG", 5, "양문형 냉장고!")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Earrings","accessory", 20000, "OST", 30, "실버색으로 반짝반짝~")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Necklace","accessory", 15000, "OST", 10, "고급스런 목걸이")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Choker","accessory", 2000, "뿔난여우", 7, "검정 끈에 하트 펜던트")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Ring","accessory", 200000, "MiniGold", 30, "14k 반지")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Notebook","computer", 1700000, "LG", 37, "Window 10 탑재되었어요")
insert into productTable(name, category, price, manufacturer, unit_in_stock, description) values ("Macbook","computer", 3000000, "Apple", 37, "Mac 노트북!")